kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: opam
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - env OPAMJOBS=40 opam --yes depext -iy `./list-overrides.sh`
- name: duniverse
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - export OPAMJOBS=40
  - opam repo add overlays .
  - opam update -uy
  - ./list-overrides.sh > pkglist.txt
  - git clone git://github.com/avsm/duniverse.git
  - cd duniverse.git && opam switch create . && opam exec -- dune build @install && sudo mv _build/default/bin/duniverse.exe /usr/bin/duniverse
  - mkdir duniverse-build
  - cd duniverse-build
  - duniverse init `cat ../pkglist.txt`
  - duniverse pull
  - opam depext -y `cat ../pkglist.txt`
  - opam install -y dune
  - opam exec -- dune build
- name: outofdate
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - ./check-upstream.sh
- name: all
  image: ocaml/opam2
  depends_on:
  - outofdate
  - duniverse
  - opam
