kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: opam
  image: ocaml/opam2:4.08
  depends_on: [ clone ]
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - opam exec -- ocaml -version
  - env OPAMERRLOGLEN=0 OPAMJOBS=40 opam --yes depext -uiy `./list-overrides.sh`
- name: platform
  image: ocaml/opam2:alpine
  commands:
  - sudo chown -R opam .
  - opam switch 4.08
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - opam install -y dune
  - eval `opam env`
  - git clone git://github.com/avsm/duniverse /tmp/duniverse && make -C /tmp/duniverse && sudo make -C /tmp/duniverse install PREFIX=/usr/bin && rm -rf /tmp/duniverse
  - PKGS=`./list-platform-binaries.sh -packages`
  - TARGETS=`./list-platform-binaries.sh -targets`
  - mkdir /tmp/duniverse-build
  - duniverse init --overlay-remote . --pin duniverse,https://github.com/avsm/duniverse.git --repo /tmp/duniverse-build $PKGS
  - cd /tmp/duniverse-build
  - duniverse pull --yes
  - opam depext -uy $PKGS
  - opam install -y dune.2.0.0
  - opam exec -- dune upgrade
  - echo "(lang dune 1.11)" > dune-project
  - echo "(name ocaml-platform)" >> dune-project
  - echo "(lang dune 1.11)" > dune-workspace
  - echo "(env (_ (flags -cclib -static)))" >> dune-workspace
  - opam exec -- dune build --profile=release $TARGETS
  - ldd _build/default/duniverse/duniverse/bin/duniverse.exe
  - ldd _build/default/duniverse/ocamlformat/src/ocamlformat.exe
  - ldd _build/default/duniverse/dune-release/bin/main.exe
- name: duniverse-vendored
  image: ocaml/opam2:alpine
  commands:
  - sudo chown -R opam .
  - opam switch 4.08
  - eval `opam env`
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam install -y dune
  - git clone git://github.com/avsm/duniverse /tmp/duniverse && make -C /tmp/duniverse && sudo make -C /tmp/duniverse install PREFIX=/usr/bin && rm -rf /tmp/duniverse
  - git clone git://github.com/avsm/duniverse /tmp/duniverse-build
  - cd /tmp/duniverse-build
  - duniverse pull --yes
  - opam install -y dune
  - opam exec -- dune upgrade
  - echo "(lang dune 1.11)" > dune-project
  - echo "(name duniverse)" >> dune-project
  - echo "(lang dune 1.11)" > dune-workspace
  - echo "(env (_ (flags -cclib -static)))" >> dune-workspace
  - opam exec -- dune build @install
  - cat duniverse.install || true
  - cp _build/install/default/bin/duniverse duniverse.exe
  - ldd duniverse.exe
  - ./duniverse.exe --help
- name: outofdate
  image: ocaml/opam2:4.08
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - ./check-upstream.sh
