kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: unix
  image: ocaml/opam2:4.07
  commands:
  - export OPAMYES=1
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add mirage-dev .
  - opam update -u
  - opam exec -- ocaml -version
  - opam depext -uiy mirage duniverse conf-pkg-config
  - eval `opam config env`
  - mkdir unix
  - cd unix
  - git clone -b dune-fix git://github.com/TheLortex/mirage-skeleton
  - make MODE=unix -C mirage-skeleton
- name: xen
  image: ocaml/opam2:4.07
  commands:
  - export OPAMYES=1
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add mirage-dev .
  - opam update -u
  - opam exec -- ocaml -version
  - opam depext -uiy mirage duniverse conf-pkg-config
  - eval `opam config env`
  - mkdir xen
  - cd xen
  - git clone -b dune-fix git://github.com/TheLortex/mirage-skeleton
  - make MODE=xen -C mirage-skeleton
- name: hvt
  image: ocaml/opam2:4.07
  commands:
  - export OPAMYES=1
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add mirage-dev .
  - opam update -u
  - opam exec -- ocaml -version
  - opam depext -uiy mirage duniverse conf-pkg-config
  - eval `opam config env`
  - mkdir hvt
  - cd hvt
  - git clone -b dune-fix git://github.com/TheLortex/mirage-skeleton
  - make MODE=hvt -C mirage-skeleton
- name: muen
  image: ocaml/opam2:4.07
  commands:
  - export OPAMYES=1
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add mirage-dev .
  - opam update -u
  - opam exec -- ocaml -version
  - opam depext -uiy mirage duniverse conf-pkg-config
  - eval `opam config env`
  - mkdir muen
  - cd muen
  - git clone -b dune-fix git://github.com/TheLortex/mirage-skeleton
  - make MODE=muen -C mirage-skeleton
- name: virtio
  image: ocaml/opam2:4.07
  commands:
  - export OPAMYES=1
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add mirage-dev .
  - opam update -u
  - opam exec -- ocaml -version
  - opam depext -uiy mirage duniverse conf-pkg-config
  - eval `opam config env`
  - mkdir virtio
  - cd virtio
  - git clone -b dune-fix git://github.com/TheLortex/mirage-skeleton
  - make MODE=virtio -C mirage-skeleton
- name: all
  image: ocaml/opam2:4.07
  depends_on:
  - unix
  - hvt
  - virtio
  - muen
  - xen