kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: opam
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - env OPAMJOBS=40 opam --yes depext -iy `./list-overrides.sh`
- name: duniverse
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam update -uy
  - opam pin add -n duniverse https://github.com/avsm/duniverse.git
  - opam depext -iy duniverse
  - sudo cp `opam config var bin`/duniverse /usr/bin/duniverse
  - opam pin remove -y duniverse
  - opam remove -ay
  - ./list-overrides.sh > pkglist.txt
  - mkdir duniverse-build
  - cd duniverse-build
  - duniverse init `grep -v opam ../pkglist.txt` -vv
  - duniverse pull -vv
  - opam depext -y `cat ../pkglist.txt`
  - opam install -y dune
  - opam exec -- dune build
- name: outofdate
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - ./check-upstream.sh
- name: all
  image: ocaml/opam2
  depends_on:
  - outofdate
  - duniverse
  - opam
