kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: opam
  image: ocaml/opam2:4.07
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - opam exec -- ocaml -version
  - env OPAMERRLONGLEN=0 OPAMJOBS=40 opam --yes depext -iy `./list-overrides.sh`
- name: platform
  image: ocaml/opam2:alpine
  commands:
  - sudo chown -R opam .
  - opam switch 4.07
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - opam pin add -n duniverse https://github.com/avsm/duniverse.git
  - env OPAMDOWNLOADJOBS=10 opam depext -iy duniverse
  - sudo cp `opam config var bin`/duniverse /usr/bin/duniverse
  - opam remove -ay
  - PKGS=`./list-platform-binaries.sh -packages`
  - TARGETS=`./list-platform-binaries.sh -targets`
  - mkdir /tmp/duniverse-build
  - duniverse init --overlay-remote . --pin duniverse,https://github.com/avsm/duniverse.git --repo /tmp/duniverse-build $PKGS
  - cd /tmp/duniverse-build
  - duniverse pull 
  - opam depext -y $PKGS
  - opam install -y dune
  - opam exec -- dune upgrade
  - echo "(lang dune 1.7)" > dune-workspace
  - echo "(env (_ (flags -cclib -static)))" >> dune-workspace
  - opam exec -- dune build --profile=release $TARGETS
  - ldd _build/default/duniverse/duniverse/bin/duniverse.exe
  - ldd _build/default/duniverse/ocamlformat/src/ocamlformat.exe
- name: duniverse
  image: ocaml/opam2:4.07
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - opam pin add -n duniverse https://github.com/avsm/duniverse.git
  - env OPAMDOWNLOADJOBS=10 opam depext -iy duniverse
  - sudo cp `opam config var bin`/duniverse /usr/bin/duniverse
  - opam pin remove -y duniverse
  - opam remove -ay
  - PKGS=`./list-overrides.sh`
  - mkdir /tmp/duniverse-build
  - duniverse init --overlay-remote . --repo /tmp/duniverse-build $PKGS 
  - cd /tmp/duniverse-build
  - duniverse pull 
  - opam depext -y $PKGS
  - opam install -y dune
  - opam exec -- dune upgrade
  - duniverse opam-install
  - opam exec -- dune build --profile=release
- name: outofdate
  image: ocaml/opam2:4.07
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - ./check-upstream.sh
- name: all
  image: ocaml/opam2:4.07
  depends_on:
  - outofdate
  - duniverse
  - opam
