kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: opam
  image: ocaml/opam2:4.10
  depends_on: [ clone ]
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - opam exec -- ocaml -version
  - env OPAMERRLOGLEN=0 OPAMJOBS=40 opam --yes depext -uiy `./list-overrides.sh`
- name: outofdate
  image: ocaml/opam2:4.10
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add overlays .
  - opam update -uy
  - ./check-upstream.sh
