kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ocaml/opam2
  commands:
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin
  - opam repo add dev .
  - opam update -uy
  - env OPAMJOBS=40 opam --yes depext -iy `find packages -type d -exec basename {} \; -mindepth 2 -maxdepth 2`
